---
title: "figure_5"
author: "Rubén Rellán-Ávarez"
output: html_document
---

```{r}

library(tidyr)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(magrittr)
library(gridExtra)
library(rmarkdown)

```




Load brachy data

```{r}
brachy <- read.csv("data/data_brachy.csv")

brachy %>%
filter(growth_media == "plate") %>%
ggplot(aes(x = das, y = length)) +
        geom_point(size = 3, alpha = .5) +
        geom_smooth() +
        labs(x = "das", y = "Depth (cm)") +
        theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank()) +
        theme_bw()

ggsave("brachy_plate_growth.pdf", height = 8, width = 6, units = "cm", 
         useDingbats = FALSE)

```

Basic comparisons at 15 DAS

```{r}
#depth

p1 <- brachy %>%
        filter(das == "15") %>%
        ggplot(aes(x = growth_media, y = length)) +
        geom_point(size = 6, alpha = .5, position = position_jitter(w = 0.2, h = 0.1)) +
        labs(x = "Growth Media", y = "Depth (cm)") +
        theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank()) +
        theme_bw()

ggsave("depth_brachy.pdf", height = 12, width = 5.5, units = "cm", 
         useDingbats = FALSE)

#lr number

p2 <- brachy %>%
        filter(das == "15") %>%
        ggplot(aes(x = growth_media, y = lr_number)) +
        geom_point(size = 6, alpha = .5, position = position_jitter(w = 0.2, h = 0.1)) +
        labs(x = "Growth Media", y = "lateral root number") +
        theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank()) +
        theme_bw()

ggsave("lr_brachy.pdf", height = 12, width = 8, units = "cm", 
         useDingbats = FALSE)
#cr number

p3 <- brachy %>%
        filter(das == "15") %>%
        ggplot(aes(x = growth_media, y = cr_number)) +
        geom_point(size = 6, alpha = .5, position = position_jitter(w = 0.2, h = 0.1)) +
        labs(x = "Growth Media", y = "crown root number") +
        theme(panel.grid.major = element_blank(), 
              panel.grid.minor = element_blank()) +
        theme_bw()

ggsave("cr_brachy.pdf", height = 12, width = 8, units = "cm", 
         useDingbats = FALSE)


# all three together
grid.arrange(p1, p2, p3, ncol=3) +

ggsave("all_brachy.pdf", height = 12, width = 12, units = "cm", 
         useDingbats = FALSE)

```




